### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by cuongvng** [sontrinh16/MachineLearningProblemSets#1]
SQL 
Task 1: Nhầm tên bảng, `CITY`, không phải `Cities`
Task 10: Điều kiện là `[aeiouAEIOU]%[aeiouAEIOU]`

**Comment by sontrinh16** [comment]
> SQL
> Task 1: Nhầm tên bảng, `CITY`, không phải `Cities`
> Task 10: Điều kiện là `[aeiouAEIOU]%[aeiouAEIOU]`

task 1 chắc em quen để tên bảng số nhiều nên nhầm :v

**Comment by vutung3196** [comment]
Ở How many people have the word Chief in their job title?
Em có thể dùng hàm `contains` trong Python nhé.
